// Folgender Code wirft einen ReferenceError

try {
  meineLieblingsFunktion();
} catch (error) {
  console.log(error.message);
}
